services:
  cms_web:
    build: .
    env_file:
      - ${ENV_FILE:-.env}
    ports:
      - ${PORT:-5080}:5080
    depends_on:
      - cms_postgres
    volumes:
      - .:/app

  cms_postgres:
    image: "postgres:16.4"
    env_file:
      - ${ENV_FILE:-.env}
    ports:
      - "5430:5432"

  cms_redis:
    image: redis:7.4
    restart: always
    ports:
      - "6370:6379"
