name: cms
channels:
- defaults
dependencies:
- flask=1.1.1
- psycopg2=2.8.4
- pyyaml=5.1.2
- werkzeug=0.16.0
- yaml
- openssl=1.1.1
- pytest=5.3.0
- pytest-cov=2.8.1
- python=3.6.8
- pip:
  - certifi
  - flask-script==2.0.6
  - flask-sqlalchemy==2.4.1
  - gunicorn==19.9.0
  - jsonschema==3.1.1
  - mohawk==1.1.0
  - redis==3.3.11
  - sqlalchemy==1.3.10
  - sqlalchemy-utils==0.33.9
  - strict-rfc3339==0.7


