database:
  dialect: postgresql
  user: $ENV{CMS_DB_USER, postgres}
  password: $ENV{CMS_DB_PWD, postgres}
  host: $ENV{CMS_DB_HOST, localhost}
  port: $ENV{CMS_DB_PORT, 5432}
  use-db: $ENV{CMS_DB_NAME, matching}
access_control:
  hawk_enabled: $ENV{CMS_AC_HAWK_ENABLED, True}
  hawk_nonce_enabled: $ENV{CMS_AC_HAWK_NONCE_ENABLED, True}
  hawk_response_header: $ENV{CMS_AC_HAWK_RESPONSE_HEADER, True}
  hawk_algorithm: $ENV{CMS_AC_HAWK_ALGORITHM, sha256}
  hawk_accept_untrusted_content: $ENV{CMS_AC_HAWK_ACCEPT_UNTRUSTED_CONTENT, False}
  hawk_localtime_offset_in_seconds: $ENV{CMS_AC_HAWK_LOCALTIME_OFFSET_IN_SECONDS, 0}
  hawk_timestamp_skew_in_seconds: $ENV{CMS_AC_HAWK_TIMESTAMP_SKEW_IN_SECONDS, 60}
cache:
  host: $ENV{CMS_CACHE_HOST, redis://localhost}
  port: $ENV{CMS_CACHE_PORT, 6379}
  password: $ENV{CMS_CACHE_PWD, }
  ssl: $ENV{CMS_CACHE_SSL, True}
