version: 2
aliases:
  - &python_version cimg/python:3.13
  - &postgresql_version cimg/postgres:17.0
  - &redis_version redis:7.4
  - &restore_pytest_cache
      restore_cache:
        name: restoring python packages from cache
        key: cms-{{ .Branch }}-{{ checksum "requirements.txt" }}
  - &cms_envs
    PIPENV_VENV_IN_PROJECT: true
    DATABASE_URL: postgresql://postgres@localhost/circle_test?sslmode=disable
    CMS_AC_ISSUERS_1_DESC: ''
    CMS_AC_ISSUERS_1_ISSUER: circle
    CMS_AC_ISSUERS_1_KEY: circle_test
    CMS_AC_ISSUERS_1_SCOPE: '*'
    CMS_CACHE_HOST: redis://localhost
    CMS_CACHE_PORT: 6379
    CMS_CACHE_PWD: ''
    CMS_DB_HOST: localhost
    CMS_DB_NAME: circle_test
    CMS_DB_PWD: ''
    CMS_DB_USER: root
    CMS_GUNICORN_PORT: 8080
jobs:
  build:
    docker:
      - image: *python_version
        environment:
          *cms_envs
    working_directory: ~/cms
    steps:
      - checkout
      - restore_cache:
          keys:
          - cms-{{ .Branch }}-{{ checksum "requirements.txt" }}-{{ .Environment.CACHE_VERSION }}
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - save_cache:
          paths:
            - venv
          key: cms-{{ .Branch }}-{{ checksum "requirements.txt" }}-{{ .Environment.CACHE_VERSION }}

  unit_test:
    docker:
      - image: *python_version
        environment:
          *cms_envs
      - image: *postgresql_version
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: circle_test
      - image: scality/s3server:latest
      - image: *redis_version
    working_directory: ~/cms
    steps:
      - checkout
      - *restore_pytest_cache
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            make unit-test
      - store_test_results:
          path: test-results/report.xml
      - store_artifacts:
          path: test-results/report.xml

  integration_test:
    docker:
      - image: *python_version
      - image: *postgresql_version
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: circle_test
      - image: scality/s3server:latest
      - image: *redis_version
    working_directory: ~/cms
    steps:
      - checkout
      - run: |
          sudo apt update
          sudo apt install postgresql-client
          sudo ln -snf /usr/bin/psql /usr/local/bin/psql
      - *restore_pytest_cache
      - run:
          environment:
            *cms_envs
          name: run tests
          command: |
            . venv/bin/activate
            make integration-test
      - store_test_results:
          path: test-results/report.xml
      - store_artifacts:
          path: test-results/report.xml

  format_checks:
    docker:
      - image: *python_version
      - image: *postgresql_version
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: circle_test
      - image: scality/s3server:latest
      - image: *redis_version
    working_directory: ~/cms
    steps:
      - checkout
      - *restore_pytest_cache
      - run:
          environment:
            *cms_envs
          name: run format checks
          command: |
            . venv/bin/activate
            make check

workflows:
  version: 2
  pr_test:
    jobs:
      - build
      - unit_test:
          requires:
            - build
      - integration_test:
          requires:
            - unit_test
